Repository nota/tatami, pull requests merged in 2019-02, with the labels that each got.

#32 focusとhoverに関する処理を外部ライブラリとして利用
  README.md
  assets/stylesheets/bootstrap/_badges.scss
  assets/stylesheets/bootstrap/_button-groups.scss
  assets/stylesheets/bootstrap/_buttons.scss
  assets/stylesheets/bootstrap/_carousel.scss
  assets/stylesheets/bootstrap/_close.scss
  assets/stylesheets/bootstrap/_dropdowns.scss
  assets/stylesheets/bootstrap/_input-groups.scss
  assets/stylesheets/bootstrap/_labels.scss
  assets/stylesheets/bootstrap/_list-group.scss
  assets/stylesheets/bootstrap/_navbar.scss
  assets/stylesheets/bootstrap/_navs.scss
  assets/stylesheets/bootstrap/_pager.scss
  assets/stylesheets/bootstrap/_pagination.scss
  assets/stylesheets/bootstrap/_scaffolding.scss
  assets/stylesheets/bootstrap/_tables.scss
  assets/stylesheets/bootstrap/_theme.scss
  assets/stylesheets/bootstrap/_thumbnails.scss
  assets/stylesheets/bootstrap/forms/normalize.scss
  assets/stylesheets/bootstrap/forms/radio-and-checkbox.scss
  assets/stylesheets/bootstrap/forms/range.scss
  assets/stylesheets/bootstrap/mixins/_background-variant.scss
  assets/stylesheets/bootstrap/mixins/_buttons.scss
  assets/stylesheets/bootstrap/mixins/_labels.scss
  assets/stylesheets/bootstrap/mixins/_list-group.scss
  assets/stylesheets/bootstrap/mixins/_text-emphasis.scss
  demo/tatami/src/client/css/btn-flat.scss
  demo/tatami/src/client/css/card.scss
  demo/tatami/src/client/js/components/forms.js
  demo/tatami/src/client/js/index.js
  demo/tatami/src/client/js/lib/use-focus.js
  package-lock.json
  package.json
Labels: ship it

#28 demo/tatami at gh-pages
  .circleci/config.yml
  .gitignore
  demo/tatami/README.md
  demo/tatami/package-lock.json
  demo/tatami/package.json
  demo/tatami/scripts/gh-pages.sh
  package-lock.json
  package.json
Labels: please review

#33 ~visibleライブラリはtatami利用側でインポートするように仕様変更
  demo/tatami/package-lock.json
  demo/tatami/package.json
  package-lock.json
  package.json
Labels: In Progress

#35 Tatami button
  assets/stylesheets/bootstrap/_button-groups.scss
  assets/stylesheets/bootstrap/_buttons.scss
  assets/stylesheets/bootstrap/_dropdowns.scss
  assets/stylesheets/bootstrap/_variables.scss
  assets/stylesheets/bootstrap/forms/form-control.scss
  assets/stylesheets/bootstrap/forms/radio-and-checkbox.scss
  assets/stylesheets/bootstrap/mixins/_buttons.scss
  demo/tatami/default.html
  demo/tatami/index.html
  demo/tatami/src/client/css/app.scss
  demo/tatami/src/client/css/btn-flat.scss
  demo/tatami/src/client/js/components/app.js
  demo/tatami/src/client/js/components/button-groups.js
  demo/tatami/src/client/js/components/buttons.js
  demo/tatami/src/client/js/components/dropdowns.js
  demo/tatami/src/client/js/components/forms.js
  demo/tatami/src/client/js/components/sandbox.js
Labels: In Progress, please review
