Repository nota/tatami, pull requests merged in 2019-03, with the labels that each got.

#36 Tatami type
  assets/stylesheets/bootstrap/_type.scss
  assets/stylesheets/bootstrap/_variables.scss
  demo/tatami/src/client/css/app.scss
  demo/tatami/src/client/js/components/type.js
Labels: In Progress, please review

#37 Tatami alert
  assets/stylesheets/bootstrap/_alerts.scss
  assets/stylesheets/bootstrap/_close.scss
  assets/stylesheets/bootstrap/_modals.scss
  assets/stylesheets/bootstrap/_variables.scss
  assets/stylesheets/bootstrap/mixins/_alerts.scss
  demo/tatami/default.html
  demo/tatami/index.html
  demo/tatami/src/client/js/components/alerts.js
  demo/tatami/src/client/js/components/forms.js
Labels: please review

#38 Tatami nav
  assets/stylesheets/bootstrap/_buttons.scss
  assets/stylesheets/bootstrap/_navs.scss
  assets/stylesheets/bootstrap/_variables.scss
  assets/stylesheets/bootstrap/forms/normalize.scss
  assets/stylesheets/bootstrap/mixins/_buttons.scss
  demo/tatami/src/client/css/bootstrap_loader.scss
  demo/tatami/src/client/js/components/alerts.js
  demo/tatami/src/client/js/components/navs.js
Labels: In Progress, please review

#42 Tatami dropdown
  assets/stylesheets/bootstrap/_dropdowns.scss
  assets/stylesheets/bootstrap/_variables.scss
  demo/tatami/src/client/js/components/dropdowns.js
Labels: please review

#47 navsでアイコンやサムネールを使えるようにする
  assets/stylesheets/bootstrap/_mixins.scss
  assets/stylesheets/bootstrap/_navs.scss
  assets/stylesheets/bootstrap/_variables.scss
  assets/stylesheets/bootstrap/mixins/_color.scss
  demo/tatami/src/client/js/components/navs.js
Labels: please review

#48 toggle-switchを追加します
  assets/stylesheets/bootstrap/_forms.scss
  assets/stylesheets/bootstrap/forms/radio-and-checkbox.scss
  assets/stylesheets/bootstrap/forms/toggle-switch.scss
  demo/tatami/src/client/js/components/forms.js
Labels: ship it

#46 Tatami auto size
  .circleci/config.yml
  assets/stylesheets/bootstrap/_button-groups.scss
  assets/stylesheets/bootstrap/_buttons.scss
  assets/stylesheets/bootstrap/_dropdowns.scss
  assets/stylesheets/bootstrap/_input-groups.scss
  assets/stylesheets/bootstrap/_mixins.scss
  assets/stylesheets/bootstrap/_navs.scss
  assets/stylesheets/bootstrap/_type.scss
  assets/stylesheets/bootstrap/forms/sizing.scss
  assets/stylesheets/bootstrap/mixins/_os.scss
  demo/tatami/src/client/js/components/app.js
  demo/tatami/src/client/js/components/button-groups.js
  demo/tatami/src/client/js/components/buttons.js
  demo/tatami/src/client/js/components/dropdowns.js
  demo/tatami/src/client/js/components/forms.js
  demo/tatami/src/client/js/components/modals.js
  demo/tatami/src/client/js/components/navs.js
  demo/tatami/src/client/js/components/sample-modals.js
  demo/tatami/src/client/js/components/type.js
  demo/tatami/src/client/js/index.js
  demo/tatami/src/client/js/lib/setup-os.js
  package-lock.json
  package.json
Labels: please review

#49 Dropdown hoverをグレーに戻す
  assets/stylesheets/bootstrap/_dropdowns.scss
  assets/stylesheets/bootstrap/_variables.scss
  demo/tatami/src/client/js/components/dropdowns.js
Labels: ship it

#52 auto-sizeはauto-lgにする
  assets/stylesheets/bootstrap/_button-groups.scss
  assets/stylesheets/bootstrap/_buttons.scss
  assets/stylesheets/bootstrap/_dropdowns.scss
  assets/stylesheets/bootstrap/_input-groups.scss
  assets/stylesheets/bootstrap/_navs.scss
  assets/stylesheets/bootstrap/_type.scss
  assets/stylesheets/bootstrap/forms/sizing.scss
  demo/tatami/src/client/js/components/app.js
  demo/tatami/src/client/js/components/button-groups.js
  demo/tatami/src/client/js/components/buttons.js
  demo/tatami/src/client/js/components/dropdowns.js
  demo/tatami/src/client/js/components/forms.js
  demo/tatami/src/client/js/components/modals.js
  demo/tatami/src/client/js/components/navs.js
  demo/tatami/src/client/js/components/sample-modals.js
Labels: ship it

#53 Dropdownのactive colorを設定
  assets/stylesheets/bootstrap/_dropdowns.scss
  assets/stylesheets/bootstrap/_variables.scss
  demo/tatami/src/client/js/components/dropdowns.js
Labels: ship it
